
# html lang
language: zh-CN

# 设置 favicon
favicon: /img/favicon.ico

# 名字logo下方
#menu:    
#  home: { path: /, fa: fa-home}
#  archive: { path: /archives/, fa: fa-archive}
#  tag: { path: /tags/, fa: fa-tags}
#  category: { path: /category/, fa: fa-folder-open}
#  about: { path: /about/, fa: fa-heart}


# 右上角的menu
menubutton: 
  tag: /tags/
  archive: /archives/
#  分类: /category/
  about: /about/
#  donate: /donate/ 
  guestbook: /guestbook/
  friends: /link/

# 座右铭
motto: Do what you love,love what you do.


# 是否打开暗黑模式
todark:
  enable: true   #是否打开暗黑模式

  
# Valine 评论系统  https://valine.js.org
valine:
  enable: true # 如果使用valine，请设置改之为true
  appid: # 你的leancloud 的appid
  appkey: # 你的leancloud 的appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size



## Post copyright
copyright:
  enable: true
  license_text: 本博客所有文章除特别声明外，均采用许可协议 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> 

# 备案:
ICP:
  enable: false
  link: 
  text: 
#  icon: /img/icp.png

# Google fonts
googlefonts:
  enable: true
  font-family: EB Garamond, Noto Serif SC, Lato, Helvetica Neue For Number, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, PingFang SC, Hiragino Sans GB, MicrMicrosoft YaHei", Helvetica Neue, Helvetica, Arial, serif, sans-serif
  link: https://fonts.googleapis.com/css?family=Noto+Serif+SC:400,700&display=swap

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css
- /css/partial/highlight.css
- https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css

# scripts loaded in the end of the body
scripts:
- /js/header.js
- /js/script.js
- https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js




# 友情链接
mylinks:
  - name: 
    avatar: 
    link: 
    info: 
    
  - name: 
    avatar: 
    link: 
    info: 
    
  - name: 
    avatar: 
    link: 
    info: 
    
