
# html lang
language: zh-CN

# 设置 favicon
favicon: /img/favicon.ico


# 设置 rss
rss: /atom.xml


# 左上角logo
logo:
  enable: true
  url: https://github.com/a2396837     # 点击图标跳转链接
  icon: fab fa-github                  # fontawesome V5 图标
  title: 一时开源一时爽，一直开源一直爽   # 鼠标移到图标显示的文字



# 顶部菜单
menu:    
  home: { path: /, fa: fab fa-fort-awesome}
  archive: { path: /archives/, fa: far fa-calendar-check}
  tag: { path: /tags/, fa: fas fa-hashtag}
#  category: { path: /category/, fa: far fa-folder-open}
  about: { path: /about/, fa: fab fa-grav}
  guestbook: { path: /guestbook/, fa: fab fa-telegram}
  friends: { path: /link/, fa: fab fa-weixin}



# 座右铭
motto: Do what you love,love what you do.


# 是否打开暗黑模式
todark:
  enable: true   #是否打开暗黑模式


# fancybox
fancybox:
  enable: true

#百度自动推送
baidu_push:
  enable: true


#谷歌分析
google_analytics: 
#百度分析
baidu_analytics: 


## Post copyright
copyright:
  enable: true
  license_text: 本博客所有文章除特别声明外，均采用许可协议 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> 转载请注明出处！

# 备案:
ICP:
  enable: true
  link: 
  text: 
#  icon: /img/icp.png

# Google fonts
googlefonts:
  enable: true
  font-family: EB Garamond, Noto Serif SC, Lato, Helvetica Neue For Number, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, PingFang SC, Hiragino Sans GB, MicrMicrosoft YaHei", Helvetica Neue, Helvetica, Arial, serif, sans-serif
  link: https://fonts.googleapis.com/css?family=Noto+Serif+SC:400,700&display=swap


# Valine 评论系统  https://valine.js.org
valine:
  enable: true # 如果使用valine，请设置改之为true
  appid: 
  appkey: 
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

  
# stylesheets loaded in the <head>
stylesheets:
- /css/style.css
- /css/partial/highlight.css
- https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css
#- https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
- https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.css


# scripts loaded in the end of the body
scripts:
- /js/header.js
- /js/script.js
- https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js



# 友情链接
mylinks:
  - name: 
    avatar: 
    link: 
    info: 
    
  - name: 
    avatar: 
    link: 
    info: 
    
  - name: 
    avatar: 
    link: 
    info: 




    
